### PR TITLE
chore: remove '@unocss/transformer-directives' and '@unocss/transformer-variant-group'

### PR DESCRIPTION
**Pull request by ottocsb**
chore(dependencies): remove '@unocss/transformer-directives' and '@unocss/transformer-variant-group', merge 'transformerVariantGroup,transformerDirectives' into main package

- Deleted '@unocss/transformer-directives' and '@unocss/transformer-variant-group' dependencies.
- Merged functionality from 'transformerVariantGroup,transformerDirectives' dependency into the main package.

Update unocss configuration to exclude 'transformerVariantGroup,transformerDirectives' dependency content.

### CODE REVIEW

**Comment by markthree** [comment]
@ottocsb thanks

**Review by markthree — COMMENTED** [review]
I think we can re `pnpm install` to trigger the update of `pnpm-lock.yaml`

**Comment by ottocsb** [comment]
Yes, you are right. I forgot to update pnpm-lock.yaml. I will make an additional commit for it.

**Comment by markthree** [comment]
Thank you, this PR is Nice

**Pull request merged**
